# fly.toml app configuration file generated for sep-backend-8er6ww-ancient-meadow-3445 on 2025-05-27T19:06:39+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sep-backend-8er6ww-ancient-meadow-3445'
primary_region = 'bom'

[build]
  dockerfile = './Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
